
import { ContructQuestion } from './construct-question';

export const questions = [
  new ContructQuestion('Por que vejo outros anúncios ofertando 350 Mega por R$99,99?', 'Porque ao contratar 250 Mega junto com outro produto (Tv a cabo, Claro Box TV ou plano celular) o cliente ganha um upgrade na sua internet, que passa a ter 350Mega de velocidade, pagando o mesmo valor do plano de 250MB. Lembrando que o cliente paga R$99,99 pelos 350 Mega + o valor do segundo produto contratado na oferta (TV, Claro Box ou celular). Nós prezamos pela transparência, por isso nosso anúncio mostra o valor final que será pago pelo cliente, sem pegadinhas.'),
  new ContructQuestion('O que são apps de conteúdo?', 'São plataformas que disponibilizam conteúdos que podem ser acessados de três maneiras: (1) via navegador de internet (Google Chrome, Mozilla, etc), (2) aplicativos mobile (Google Play e Apple Store) e (3) aplicativos de TV como Amazom Stick TV.'),
  new ContructQuestion('O preço vai aumentar?', 'Não. O valor exibido é exatamente o que constará na fatura em todos os meses.'),
  new ContructQuestion('Pago alguma taxa no momento da instalação?', 'Não. Nossos planos são isentos de taxas de adesão e instalação. O cliente só começa a pagar o valor contratado no primeiro vencimento escolhido, geralmente de 30 a 45 dias após a data de instalação.'),
  new ContructQuestion('Como consigo assistir o Claro Vídeo, Now e aos canais Discovery+ que ganhei como degustação?', 'Você pode assistir pelo computador, celular ou Smart TV, via app ou site, pela opção de login via "operadora", usando sempre o seu login de cliente Claro (mesmo login usado no app Minha Claro Residencial). Para Discovery + basta entrar no site do Discovery+ e se registrar usando também seu login de cliente Claro. Usuários do Claro Box TV também podem assistir o streaming pela própria caixinha através do canal 834.'),
  new ContructQuestion('O que é Claro Box TV?', 'A TV Box Claro funciona de forma semelhante à TV por assinatura convencional. Contudo, não necessita de um cabo ou antena parabólica para ter acesso aos canais, e sim uma conexão Wi-Fi e uma TV com entrada HDMI. A instalação é tão simples que é feita pelo próprio cliente, que ainda recebe um controle remoto por comando de voz sem custo adicional. Vai passar o fim de semana fora? Pode levar sua Claro Box TV para onde você for e curtir sua programação normalmente, desde que no local haja conexão Wi-Fi e uma Tv com entrada HDMI.'),
  new ContructQuestion('Quais canais vem no Claro Box TV?', 'São duas opções de planos disponíveis para contratar junto ao plano de internet: 1) com canais GloboPlay, Claro Vídeo e Now e abertos (exceto Globo) por R$44,99 2) com a grade Top HD (mais de 100 canais entre infantis, esportes, documentários, filmes e séries, além de canais abertos, inclusive Globo) por R$79,99'),
  new ContructQuestion('O Claro Box TV possui fidelidade?', 'Não. Se contratado junto ao plano de internet não há fidelidade, portanto o Claro Box Tv pode ser cancelado a qualquer momento, sem multas e o equipamento devolvido à Claro.'),
  new ContructQuestion('Se eu pagar via boleto/fatura mensal pago o mesmo valor do anúncio?', 'Não. Os valores no anúncio são para pagamento via débito em conta corrente ou poupança. Para pagamento via boleto perde-se o desconto e o cliente passa a pagar valor acrescido de R$5,00 na contratação da internet avulsa ou de R$10,00 na contratação de Internet + TV a cabo ou Claro Box TV.'),
  new ContructQuestion('Posso alterar a forma de pagamento após a instalação do meu plano?', '- Sim, data de vencimento e a forma de pagamento podem ser alteradas via app Minha Claro Residencial. Lembrando que, se a forma escolhida inicial era débito em conta, ao alterar para boleto perde-se o desconto de R$5,00 ou R$10,00 passando a pagar valor de boleto. O inverso acontece se, contratando inicialmente para pagamento no boleto e, posteriormente alterar para débito em conta, o cliente passará a pagar o valor com desconto.'),
  new ContructQuestion('Posso confiar em solicitar meu plano por este canal?', 'Sim. A Claro possui vendedores e consultores independentes que atuam por todo o Brasil. Após fazer seu cadastro, o cliente recebe um contato da empresa, no prazo de 4h a 24h úteis, para confirmação de seus dados, plano contratado, data de instalação, além de receber também uma cópia do contrato com a Claro contendo todas as informações sobre a contratação do seu plano diretamente no e-mail informado no momento do cadastro, para conferência de produtos e valores.'),
  new ContructQuestion('Como faço pra alterar a data da instalação?', 'Pelo app Minha Claro Residencial você pode acompanhar todo o processo de instalação, inclusive alterar a data e horário, caso precise. Por lá você também acompanha o deslocamento do técnico até sua residência, vê a placa do carro e até a foto do técnico que vai realizar sua instalação, tudo para sua segurança. Após a instalação, pelo app você também acessa a segunda via da sua fatura, altera dados como vencimento, forma de pagamento e solicita visita técnica.'),
];